/* Generated by tests/reference/90_offset_curves.wls (Mathematica, 30 digits). */
static double const ref_parabola_t[] = { 0.30839476586478002e0, 0.69160523413521998e0 };
static double const ref_parabola_p[] = { 0.22509823218728276e0, 0.94055078897614961e0, -0.22509823218728276e0, 0.94055078897614961e0 };
static double const ref_parabola_evolute_vertex[] = { 0.0, 0.50000000000000000e0 };
static double const ref_s_right_t[] = { 0.12427961410972082e0, 0.26053860703059776e0 };
static double const ref_s_right_p[] = { 0.71492508567062617e0, -0.22322807143505333e-2, 0.60296452429576191e0, -0.19175393615045263e-1 };
static double const ref_s_left_t[] = { 0.73946139296940224e0, 0.87572038589027918e0 };
static double const ref_s_left_p[] = { 0.23970354757042381e1, 0.19175393615045263e-1, 0.22850749143293738e1, 0.22322807143505333e-2 };
