#include "qaws_status.h"

const char *qaws_status_to_string(qaws_status status)
{
	switch (status) {
	case QAWS_STATUS_OK:
		return "QAWS_STATUS_OK";
	case QAWS_STATUS_INVALID_ARGUMENT:
		return "QAWS_STATUS_INVALID_ARGUMENT";
	case QAWS_STATUS_INVALID_DIMENSION:
		return "QAWS_STATUS_INVALID_DIMENSION";
	case QAWS_STATUS_INVALID_DEGREE:
		return "QAWS_STATUS_INVALID_DEGREE";
	case QAWS_STATUS_INVALID_CONTROL_POINT_COUNT:
		return "QAWS_STATUS_INVALID_CONTROL_POINT_COUNT";
	case QAWS_STATUS_INVALID_KNOT_COUNT:
		return "QAWS_STATUS_INVALID_KNOT_COUNT";
	case QAWS_STATUS_INVALID_KNOT_VECTOR:
		return "QAWS_STATUS_INVALID_KNOT_VECTOR";
	case QAWS_STATUS_INVALID_WEIGHT_COUNT:
		return "QAWS_STATUS_INVALID_WEIGHT_COUNT";
	case QAWS_STATUS_INVALID_PARAMETER_RANGE:
		return "QAWS_STATUS_INVALID_PARAMETER_RANGE";
	case QAWS_STATUS_OUT_OF_RANGE:
		return "QAWS_STATUS_OUT_OF_RANGE";
	case QAWS_STATUS_UNSUPPORTED_OPERATION:
		return "QAWS_STATUS_UNSUPPORTED_OPERATION";
	case QAWS_STATUS_DEGENERATE_CURVE:
		return "QAWS_STATUS_DEGENERATE_CURVE";
	case QAWS_STATUS_NUMERICAL_FAILURE:
		return "QAWS_STATUS_NUMERICAL_FAILURE";
	case QAWS_STATUS_BUFFER_TOO_SMALL:
		return "QAWS_STATUS_BUFFER_TOO_SMALL";
	case QAWS_STATUS_ALLOCATION_FAILURE:
		return "QAWS_STATUS_ALLOCATION_FAILURE";
	case QAWS_STATUS_INTERNAL_ERROR:
		return "QAWS_STATUS_INTERNAL_ERROR";
	case QAWS_STATUS_EXACT_UNSUPPORTED:
		return "QAWS_STATUS_EXACT_UNSUPPORTED";
	case QAWS_STATUS_EXACT_RANGE_EXCEEDED:
		return "QAWS_STATUS_EXACT_RANGE_EXCEEDED";
	case QAWS_STATUS_EXACT_INCOMPATIBLE_SPACE:
		return "QAWS_STATUS_EXACT_INCOMPATIBLE_SPACE";
	case QAWS_STATUS_CERTIFICATION_FAILED:
		return "QAWS_STATUS_CERTIFICATION_FAILED";
	default:
		return "QAWS_STATUS_UNKNOWN";
	}
}
