#!/usr/bin/env python3
"""Generate a single-header / single-implementation pair from the Qaws tree.

Produces two files:

  qaws.h  -- the complete public API (every public header inlined)
  qaws.c  -- the complete implementation (internal headers + all .c bodies)

Consumers then need nothing but those two files: drop them into any project,
compile qaws.c, include qaws.h. No build system, no include paths.

    python buildsystem/amalgamate.py --output-dir build/amalgam [--simd]

Quoted includes are inlined recursively and each file is emitted at most once,
which matches the include-guard semantics of the original tree. Angle-bracket
includes are left untouched and in place: several of them sit inside ISA
detection blocks and must stay conditional.
"""

import argparse
import os
import re
import sys

INCLUDE_RE = re.compile(r'^[ \t]*#[ \t]*include[ \t]*"([^"]+)"[ \t]*\r?$')

# Public umbrella header. Everything reachable from here forms qaws.h.
PUBLIC_ROOT = 'qaws.h'

# Bootstrap headers for the shader backends. They select a non-C backend at
# include time and must not be pulled into the C amalgamation.
EXCLUDED = {'qaws_hlsl.h', 'qaws_glsl.h', 'qaws_halide.h'}


class Amalgamator:
    def __init__(self, root):
        self.root = os.path.abspath(root)
        self.seen = set()
        self.missing = []

    def _rel(self, path):
        return os.path.relpath(path, self.root).replace(os.sep, '/')

    def inline(self, path, out):
        """Append path to out, recursively inlining its quoted includes."""
        path = os.path.normpath(path)
        key = os.path.normcase(path)
        if key in self.seen:
            return
        self.seen.add(key)

        with open(path, encoding='utf-8') as fh:
            lines = fh.read().splitlines()

        out.append('/* ==== begin %s ==== */' % self._rel(path))
        here = os.path.dirname(path)
        for line in lines:
            match = INCLUDE_RE.match(line)
            if not match:
                out.append(line)
                continue

            target = match.group(1)
            if os.path.basename(target) in EXCLUDED:
                continue

            resolved = os.path.join(here, target)
            if not os.path.isfile(resolved):
                resolved = os.path.join(self.root, target)
            if not os.path.isfile(resolved):
                self.missing.append((self._rel(path), target))
                out.append(line)
                continue

            self.inline(resolved, out)
        out.append('/* ==== end %s ==== */' % self._rel(path))


def collect_sources(root, with_simd):
    """All .c files, in the same order the build systems list them."""
    sources = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        rel_dir = os.path.relpath(dirpath, root).replace(os.sep, '/')
        if rel_dir == 'batch' and not with_simd:
            continue
        for name in sorted(filenames):
            if name.endswith('.c'):
                sources.append(os.path.join(dirpath, name))
    return sources


def banner(kind, with_simd):
    return [
        '/*',
        ' * Qaws -- amalgamated %s.' % kind,
        ' *',
        ' * Generated by buildsystem/amalgamate.py -- do not edit.',
        ' * Edit the sources under src/qaws/ and regenerate.',
        ' *',
        ' * SIMD batch evaluation: %s' % ('included' if with_simd else 'excluded'),
        ' *',
        ' * Define QAWS_SCALAR_IS_FLOAT=1 for float, 0 for double, before',
        ' * including this file. It must match between qaws.h and qaws.c.',
        ' */',
        '',
    ]


def write_if_changed(path, text):
    """Write text to path only if it differs. Returns True if it wrote.

    Build steps run this on every build; leaving an identical ~1 MiB file
    untouched keeps its timestamp and avoids a pointless recompile.
    """
    if os.path.isfile(path):
        with open(path, encoding='utf-8', newline='') as fh:
            if fh.read() == text:
                return False
    with open(path, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(text)
    return True


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--source-dir', default=None,
                        help='Qaws source root (default: <repo>/src/qaws)')
    parser.add_argument('--output-dir', required=True,
                        help='Directory to write qaws.h and qaws.c into')
    parser.add_argument('--simd', action='store_true',
                        help='Include the batch/ SIMD sources in qaws.c')
    args = parser.parse_args(argv)

    source_dir = args.source_dir
    if source_dir is None:
        repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        source_dir = os.path.join(repo, 'src', 'qaws')
    source_dir = os.path.abspath(source_dir)

    root_header = os.path.join(source_dir, PUBLIC_ROOT)
    if not os.path.isfile(root_header):
        parser.error('no %s under %s' % (PUBLIC_ROOT, source_dir))

    os.makedirs(args.output_dir, exist_ok=True)

    # Pass 1: the public header.
    header = Amalgamator(source_dir)
    header_lines = banner('public header', args.simd)
    header.inline(root_header, header_lines)

    # Pass 2: the implementation. It opens with qaws.h, so everything already
    # emitted there is carried over as seen and will not be duplicated.
    impl = Amalgamator(source_dir)
    impl.seen = set(header.seen)
    impl_lines = banner('implementation', args.simd)
    impl_lines += ['#include "qaws.h"', '']

    sources = collect_sources(source_dir, args.simd)
    for src in sources:
        impl.inline(src, impl_lines)

    missing = header.missing + impl.missing
    if missing:
        for where, what in missing:
            sys.stderr.write('amalgamate: unresolved include "%s" in %s\n' % (what, where))
        return 1

    out_header = os.path.join(args.output_dir, 'qaws.h')
    out_impl = os.path.join(args.output_dir, 'qaws.c')
    header_written = write_if_changed(out_header, '\n'.join(header_lines) + '\n')
    impl_written = write_if_changed(out_impl, '\n'.join(impl_lines) + '\n')

    print('amalgamate: %s (%.1f KiB)%s'
          % (out_header, os.path.getsize(out_header) / 1024.0,
             '' if header_written else ' [unchanged]'))
    print('amalgamate: %s (%.1f KiB, %d sources)%s'
          % (out_impl, os.path.getsize(out_impl) / 1024.0, len(sources),
             '' if impl_written else ' [unchanged]'))
    return 0


if __name__ == '__main__':
    sys.exit(main())
