# Generate a single-header / single-implementation pair from the Qaws tree.
#
# Produces two files:
#
#   qaws.h  -- the complete public API (every public header inlined)
#   qaws.c  -- the complete implementation (internal headers + all .c bodies)
#
# Consumers then need nothing but those two files: drop them into any project,
# compile qaws.c, include qaws.h. No build system, no include paths.
#
#   cmake -DQAWS_OUTPUT_DIR=build/amalgam [-DQAWS_SOURCE_DIR=src/qaws] [-DQAWS_SIMD=ON]
#         -P buildsystem/amalgamate.cmake
#
# Quoted includes are inlined recursively and each file is emitted at most once,
# which matches the include-guard semantics of the original tree. Angle-bracket
# includes are left untouched and in place: several of them sit inside ISA
# detection blocks and must stay conditional.

cmake_minimum_required(VERSION 3.16)

if(NOT QAWS_OUTPUT_DIR)
  message(FATAL_ERROR "amalgamate: pass -DQAWS_OUTPUT_DIR=<dir>")
endif()
if(NOT QAWS_SOURCE_DIR)
  get_filename_component(QAWS_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/../src/qaws" ABSOLUTE)
endif()
get_filename_component(QAWS_SOURCE_DIR "${QAWS_SOURCE_DIR}" ABSOLUTE)
get_filename_component(QAWS_OUTPUT_DIR "${QAWS_OUTPUT_DIR}" ABSOLUTE)

# Bootstrap headers for the shader backends. They select a non-C backend at
# include time and must not be pulled into the C amalgamation.
set(_AM_EXCLUDED qaws_hlsl.h qaws_glsl.h qaws_halide.h)

# An include line: optional blanks, #include "target", optional blanks, end of line.
set(_AM_INCLUDE_RE "\n[ \t]*#[ \t]*include[ \t]*\"([^\"\n]+)\"[ \t]*\n")

set_property(GLOBAL PROPERTY AM_SEEN "")
set_property(GLOBAL PROPERTY AM_MISSING "")

function(_am_rel path out)
  file(RELATIVE_PATH rel "${QAWS_SOURCE_DIR}" "${path}")
  set(${out} "${rel}" PARENT_SCOPE)
endfunction()

# Appends path to the variable named by out_var, inlining its quoted includes.
function(_am_inline path out_var)
  get_filename_component(path "${path}" ABSOLUTE)
  string(TOLOWER "${path}" key)
  get_property(seen GLOBAL PROPERTY AM_SEEN)
  list(FIND seen "${key}" found)
  if(NOT found EQUAL -1)
    set(${out_var} "" PARENT_SCOPE)
    return()
  endif()
  set_property(GLOBAL APPEND PROPERTY AM_SEEN "${key}")

  file(READ "${path}" text)
  string(REPLACE "\r\n" "\n" text "${text}")
  string(REGEX REPLACE "\n$" "" text "${text}")
  get_filename_component(here "${path}" DIRECTORY)
  _am_rel("${path}" rel)

  set(out "/* ==== begin ${rel} ==== */")
  # A leading newline lets the first line match the include pattern; the
  # pattern eats the newline after the include, which is put back each time.
  set(text "\n${text}\n")
  while(TRUE)
    string(REGEX MATCH "${_AM_INCLUDE_RE}" match "${text}")
    if(NOT match)
      break()
    endif()
    set(target "${CMAKE_MATCH_1}")
    string(FIND "${text}" "${match}" pos)
    string(SUBSTRING "${text}" 0 ${pos} prefix)
    string(APPEND out "${prefix}")
    string(LENGTH "${match}" mlen)
    math(EXPR rest "${pos} + ${mlen}")
    string(SUBSTRING "${text}" ${rest} -1 text)
    set(text "\n${text}")

    get_filename_component(base "${target}" NAME)
    list(FIND _AM_EXCLUDED "${base}" excluded)
    if(NOT excluded EQUAL -1)
      continue()
    endif()
    set(resolved "${here}/${target}")
    if(NOT EXISTS "${resolved}")
      set(resolved "${QAWS_SOURCE_DIR}/${target}")
    endif()
    if(NOT EXISTS "${resolved}")
      set_property(GLOBAL APPEND PROPERTY AM_MISSING "\"${target}\" in ${rel}")
      string(APPEND out "\n#include \"${target}\"")
      continue()
    endif()
    _am_inline("${resolved}" inner)
    if(NOT inner STREQUAL "")
      string(APPEND out "\n${inner}")
    endif()
  endwhile()
  # what is left starts with a newline and ends with the one added above
  string(REGEX REPLACE "\n$" "" text "${text}")
  string(APPEND out "${text}\n/* ==== end ${rel} ==== */")
  set(${out_var} "${out}" PARENT_SCOPE)
endfunction()

# All .c files: a directory's own files first, then its subdirectories, both
# sorted (the order the build systems list them).
function(_am_collect dir out_var)
  file(GLOB files LIST_DIRECTORIES false "${dir}/*.c")
  list(SORT files)
  file(GLOB children LIST_DIRECTORIES true "${dir}/*")
  list(SORT children)
  foreach(child IN LISTS children)
    if(IS_DIRECTORY "${child}")
      get_filename_component(name "${child}" NAME)
      if(name STREQUAL "batch" AND NOT QAWS_SIMD AND dir STREQUAL QAWS_SOURCE_DIR)
        continue()
      endif()
      _am_collect("${child}" sub)
      list(APPEND files ${sub})
    endif()
  endforeach()
  set(${out_var} "${files}" PARENT_SCOPE)
endfunction()

function(_am_banner kind out_var)
  if(QAWS_SIMD)
    set(simd "included")
  else()
    set(simd "excluded")
  endif()
  set(${out_var}
"/*
 * Qaws -- amalgamated ${kind}.
 *
 * Generated by buildsystem/amalgamate.cmake -- do not edit.
 * Edit the sources under src/qaws/ and regenerate.
 *
 * SIMD batch evaluation: ${simd}
 *
 * Define QAWS_SCALAR_IS_FLOAT=1 for float, 0 for double, before
 * including this file. It must match between qaws.h and qaws.c.
 */
" PARENT_SCOPE)
endfunction()

# Writes text to path only if it differs: an identical ~1 MiB file keeps its
# timestamp and avoids a pointless recompile.
function(_am_write path text)
  if(EXISTS "${path}")
    file(READ "${path}" old)
    if(old STREQUAL text)
      message(STATUS "amalgamate: ${path} [unchanged]")
      return()
    endif()
  endif()
  file(WRITE "${path}" "${text}")
  string(LENGTH "${text}" size)
  math(EXPR kib "${size} / 1024")
  message(STATUS "amalgamate: ${path} (${kib} KiB)")
endfunction()

if(NOT EXISTS "${QAWS_SOURCE_DIR}/qaws.h")
  message(FATAL_ERROR "amalgamate: no qaws.h under ${QAWS_SOURCE_DIR}")
endif()
file(MAKE_DIRECTORY "${QAWS_OUTPUT_DIR}")

# Pass 1: the public header.
_am_banner("public header" header)
_am_inline("${QAWS_SOURCE_DIR}/qaws.h" body)
string(APPEND header "${body}\n")

# Pass 2: the implementation. It opens with qaws.h, so everything already
# emitted there stays seen and is not duplicated.
_am_banner("implementation" impl)
string(APPEND impl "#include \"qaws.h\"\n\n")
_am_collect("${QAWS_SOURCE_DIR}" sources)
list(LENGTH sources source_count)
foreach(src IN LISTS sources)
  _am_inline("${src}" body)
  if(NOT body STREQUAL "")
    string(APPEND impl "${body}\n")
  endif()
endforeach()

get_property(missing GLOBAL PROPERTY AM_MISSING)
if(missing)
  foreach(m IN LISTS missing)
    message(SEND_ERROR "amalgamate: unresolved include ${m}")
  endforeach()
  message(FATAL_ERROR "amalgamate: unresolved includes")
endif()

_am_write("${QAWS_OUTPUT_DIR}/qaws.h" "${header}")
_am_write("${QAWS_OUTPUT_DIR}/qaws.c" "${impl}")
message(STATUS "amalgamate: ${source_count} sources")
